name: Build and Ping FeaturePeek
on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Build
      run: bundle exec jekyll build
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci) 
